name: PyLMS CI

on: 
  push:
    branches:
      - 'main'
  pull_request: 
    types: [ opened ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
    - name: check-format
      run: |
          make check-format
    - name: tests
      run: |
        make test
    - name: build
      run: |
        make build
